# 0.0.2 Abayro CI
version: 2
jobs:
  # build:
  #   #...
  deploy:
    machine:
      enabled: true
    steps:
      # - add ssh keys
      - run:
          name: Deploy Over SSH
          command: |
            ssh -t $USER@$HOST "cd ./abayro && sh -ac '. ./.env; ./deploy/pull.sh'"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      # - build
      - deploy:
          filters:
            branches:
              only: master
